<-------------------------------------HYPATIA RESEARCH INSTITUTE MEXICO------------------------------------------->
<---------------------------------------------Experiment Report--------------------------------------------------->

Date: August 29th 2024
Weather: 20ºC	Place: Azcapotzalco, Mexico City
Hour: 16:20
Initial observations: Problema de placa MEGA fue desconocida por la computadora en los puertos asignados. 

<----------------------------------------------MEASUREMENTS-------------------------INICIO----------FIN-----------> 
 
10:45AM Medicion Linea Base Pre-experimental (001mednegra.txt) ⚫:		 10:45:52.738 - 11:50:38.600
11:05AM Medicion Linea Base Pre-experimental (002mednegra.txt) ⚫:		 

11:25AM Medición Linea Base 1 :(01mednegra.txt)	⚫:				 11:25:28.557 - 12:30:02.294
11:45AM Medición Experimental Intervención 1 - Verde:🟢  (01medverde.txt):		 11:50:50.272 - 12:55:38.668
12:05PM Medición Linea Base 2 :(02mednegra.txt)	⚫:				 12:05:13.107 - 12:10:13.372
12:25PM Medición Experimental Intervención 2 - Verde:🟢  (02medverde.txt):		 12:25:02.779 - 12:30:03.488
12:45PM Medición Linea Base 3 :(03mednegra.txt)	⚫:				 12:45:08.753 - 12:50:09.133
01:05PM Medición Experimental Intervención 3 - Verde:🟢  (03medverde.txt):		 01:05:40.401 - 01:10:40.431
01:25PM Medición Linea Base 4 :(04mednegra.txt)	⚫:				 01:25:07.047 - 01:30:07.414

01:45PM Medicion Linea Base Post-experimental (003mednegra.txt)⚫:		 01:45:15.678 - 01:50:15.682


<-----------------------------------------------OBSERVATIONS-------------------------------------------------------->
01REV: Problema de placa MEGA fue desconocida por la computadora en los puertos asignados. Se realizó un reinicio del 
ordenador para verificar si lo que fallaba era la placa. Al parecer fue la computadora. Sigue en obaservacion 


By: Berenice Ávila-S
<-----------------------------------------------FIN DE JORNADA------------------------------------------------------->